
  - name: install apache2 package
    tags: apache2,ubuntu
    apt:  
      name: apache2
      state: latest  

  - name: add php support for apache
    apt: 
      name: libapache2-mod-php
      state: latest
      
  - name : start apache
    service:
     name: apache2
     state: started 
     enabled: yes


  - name: copy default html file for site
    tags: apache2,httpd
    copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644

